package capa_presentacion;

import capa_presentacion.mantenimiento.*;
import capa_presentacion.reportes.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Fernandez Reyes
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setResizable(false);
        jdInicionSesion objForm = new jdInicionSesion(null, true);
        objForm.setLocationRelativeTo(objForm);
        this.setLocationRelativeTo(null);
        objForm.setResizable(false);
        objForm.setIconImage( new ImageIcon("src/Recursos/unprg.png").getImage());
        this.setIconImage( new ImageIcon("src/Recursos/unprg.png").getImage());
        objForm.setVisible(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSistemaCerrarSesion = new javax.swing.JMenuItem();
        mnuSistemaSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuManUsuarios = new javax.swing.JMenuItem();
        mnuManMarcas = new javax.swing.JMenuItem();
        mnuManCategorias = new javax.swing.JMenuItem();
        mnuManProducto = new javax.swing.JMenuItem();
        mnuManCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuOpVenta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuRepUsuarios = new javax.swing.JMenuItem();
        mnuRepUsuariosTipo = new javax.swing.JMenuItem();
        mnuRepMarcas = new javax.swing.JMenuItem();
        mnuRepCategorias = new javax.swing.JMenuItem();
        jdRepProductos = new javax.swing.JMenuItem();
        mnuRepVentas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: Menu Principal by Fernandez :.");

        jMenuBar1.setForeground(new java.awt.Color(0, 102, 153));

        jMenu1.setForeground(new java.awt.Color(0, 102, 153));
        jMenu1.setText("Sistema");

        mnuSistemaCerrarSesion.setForeground(new java.awt.Color(0, 102, 153));
        mnuSistemaCerrarSesion.setText("Cerrar Sesion");
        mnuSistemaCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSistemaCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSistemaCerrarSesion);

        mnuSistemaSalir.setForeground(new java.awt.Color(0, 102, 153));
        mnuSistemaSalir.setText("Salir");
        mnuSistemaSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSistemaSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSistemaSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 102, 153));
        jMenu2.setText("Mantenimiento");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        mnuManUsuarios.setForeground(new java.awt.Color(0, 102, 153));
        mnuManUsuarios.setText("Usuarios");
        mnuManUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManUsuarios);

        mnuManMarcas.setForeground(new java.awt.Color(0, 102, 153));
        mnuManMarcas.setText("Marcas");
        mnuManMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManMarcasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManMarcas);

        mnuManCategorias.setForeground(new java.awt.Color(0, 102, 153));
        mnuManCategorias.setText("Categoria");
        mnuManCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManCategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManCategorias);

        mnuManProducto.setForeground(new java.awt.Color(0, 102, 153));
        mnuManProducto.setText("Producto");
        mnuManProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManProductoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManProducto);

        mnuManCliente.setForeground(new java.awt.Color(0, 102, 153));
        mnuManCliente.setText("Cliente");
        mnuManCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManClienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 102, 153));
        jMenu3.setText("Operaciones");

        mnuOpVenta.setForeground(new java.awt.Color(0, 102, 153));
        mnuOpVenta.setText("Venta");
        mnuOpVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpVentaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuOpVenta);

        jMenuBar1.add(jMenu3);

        jMenu5.setForeground(new java.awt.Color(0, 102, 153));
        jMenu5.setText("Reportes");

        mnuRepUsuarios.setForeground(new java.awt.Color(0, 102, 153));
        mnuRepUsuarios.setText("Usuarios");
        mnuRepUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepUsuariosActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRepUsuarios);

        mnuRepUsuariosTipo.setForeground(new java.awt.Color(0, 102, 153));
        mnuRepUsuariosTipo.setText("Usuarios por tipo");
        mnuRepUsuariosTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepUsuariosTipoActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRepUsuariosTipo);

        mnuRepMarcas.setForeground(new java.awt.Color(0, 102, 153));
        mnuRepMarcas.setText("Marcas");
        mnuRepMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepMarcasActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRepMarcas);

        mnuRepCategorias.setForeground(new java.awt.Color(0, 102, 153));
        mnuRepCategorias.setText("Categorias");
        mnuRepCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepCategoriasActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRepCategorias);

        jdRepProductos.setForeground(new java.awt.Color(0, 102, 153));
        jdRepProductos.setText("Productos");
        jdRepProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdRepProductosActionPerformed(evt);
            }
        });
        jMenu5.add(jdRepProductos);

        mnuRepVentas.setForeground(new java.awt.Color(0, 102, 153));
        mnuRepVentas.setText("Ventas");
        mnuRepVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepVentasActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRepVentas);

        jMenuBar1.add(jMenu5);

        jMenu4.setForeground(new java.awt.Color(0, 102, 153));
        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSistemaSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSistemaSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_mnuSistemaSalirActionPerformed

    private void mnuManUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManUsuariosActionPerformed

        frmManUsuario objForm = new frmManUsuario(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuManUsuariosActionPerformed

    private void mnuSistemaCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSistemaCerrarSesionActionPerformed
        
        // Ocultar la ventana del menu principal
        this.setVisible(false);
        
        // Mostrar la ventana de inicio de sesion
        jdInicionSesion objLogin = new jdInicionSesion(null, true);
        objLogin.setLocationRelativeTo(null);
        objLogin.setResizable(false);
        objLogin.setIconImage( new ImageIcon("src/img/unprg.png").getImage());
        objLogin.setVisible(true);
        
        // en caso el usuario cierre la ventana de login sin autenticarse,
        // en caso de loguearse correctamente, mostrar nuevamente el menu
        this.setVisible(true);
    }//GEN-LAST:event_mnuSistemaCerrarSesionActionPerformed

    private void mnuRepUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepUsuariosActionPerformed

        jdRepUsuarios objForm = new jdRepUsuarios(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRepUsuariosActionPerformed

    private void mnuRepUsuariosTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepUsuariosTipoActionPerformed

        jdRepUsuPorTipo objForm = new jdRepUsuPorTipo(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRepUsuariosTipoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void mnuManMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManMarcasActionPerformed
         
        frmManMarca objForm = new frmManMarca(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuManMarcasActionPerformed

    private void mnuManCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManCategoriasActionPerformed
        
        fmrManCategoria objForm = new fmrManCategoria(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuManCategoriasActionPerformed

    private void mnuRepMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepMarcasActionPerformed
        
        jdRepMarcas objForm = new jdRepMarcas(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRepMarcasActionPerformed

    private void mnuRepCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepCategoriasActionPerformed
        
        jdRepCategorias objForm = new jdRepCategorias(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRepCategoriasActionPerformed

    private void mnuManProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManProductoActionPerformed
        
        frmManProducto objForm = new frmManProducto(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuManProductoActionPerformed

    private void jdRepProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdRepProductosActionPerformed
        
        jdRepProductos objForm = new jdRepProductos(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_jdRepProductosActionPerformed

    private void mnuOpVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpVentaActionPerformed
        
        jdVenta objForm = new jdVenta(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuOpVentaActionPerformed

    private void mnuManClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManClienteActionPerformed
        frmManCliente objForm = new frmManCliente(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuManClienteActionPerformed

    private void mnuRepVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepVentasActionPerformed
        jdRepVentas objForm = new jdRepVentas(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRepVentasActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jdRepProductos;
    private javax.swing.JMenuItem mnuManCategorias;
    private javax.swing.JMenuItem mnuManCliente;
    private javax.swing.JMenuItem mnuManMarcas;
    private javax.swing.JMenuItem mnuManProducto;
    private javax.swing.JMenuItem mnuManUsuarios;
    private javax.swing.JMenuItem mnuOpVenta;
    private javax.swing.JMenuItem mnuRepCategorias;
    private javax.swing.JMenuItem mnuRepMarcas;
    private javax.swing.JMenuItem mnuRepUsuarios;
    private javax.swing.JMenuItem mnuRepUsuariosTipo;
    private javax.swing.JMenuItem mnuRepVentas;
    private javax.swing.JMenuItem mnuSistemaCerrarSesion;
    private javax.swing.JMenuItem mnuSistemaSalir;
    // End of variables declaration//GEN-END:variables
}
