package capa_presentacion;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Fernandez Reyes
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jdInicionSesion objForm = new jdInicionSesion(null, true);
        objForm.setLocationRelativeTo(objForm);
        objForm.setTitle("Login by Fernandez");
        this.setTitle("Menu Principal by Fernandez");
        objForm.setIconImage( new ImageIcon("src/img/unprg.png").getImage());
        this.setIconImage( new ImageIcon("src/img/unprg.png").getImage());
        objForm.setVisible(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSistemaCerrarSesion = new javax.swing.JMenuItem();
        mnuSistemaSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuManUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        mnuRepUsuarios = new javax.swing.JMenuItem();
        mnuRepUsuariosTipo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Sistema");

        mnuSistemaCerrarSesion.setText("Cerrar Sesion");
        mnuSistemaCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSistemaCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSistemaCerrarSesion);

        mnuSistemaSalir.setText("Salir");
        mnuSistemaSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSistemaSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSistemaSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimiento");

        mnuManUsuarios.setText("Usuarios");
        mnuManUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManUsuarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Operaciones");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Reportes");

        mnuRepUsuarios.setText("Usuarios");
        mnuRepUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepUsuariosActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRepUsuarios);

        mnuRepUsuariosTipo.setText("Usuarios por tipo");
        mnuRepUsuariosTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepUsuariosTipoActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRepUsuariosTipo);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSistemaSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSistemaSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_mnuSistemaSalirActionPerformed

    private void mnuManUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManUsuariosActionPerformed

        frmManUsuario objForm = new frmManUsuario(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuManUsuariosActionPerformed

    private void mnuSistemaCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSistemaCerrarSesionActionPerformed
        
        
    }//GEN-LAST:event_mnuSistemaCerrarSesionActionPerformed

    private void mnuRepUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepUsuariosActionPerformed

        jdRepUsuarios objForm = new jdRepUsuarios(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRepUsuariosActionPerformed

    private void mnuRepUsuariosTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepUsuariosTipoActionPerformed

        jdRepUsuPorTipo objForm = new jdRepUsuPorTipo(this, true);
        objForm.setLocationRelativeTo(this);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRepUsuariosTipoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuManUsuarios;
    private javax.swing.JMenuItem mnuRepUsuarios;
    private javax.swing.JMenuItem mnuRepUsuariosTipo;
    private javax.swing.JMenuItem mnuSistemaCerrarSesion;
    private javax.swing.JMenuItem mnuSistemaSalir;
    // End of variables declaration//GEN-END:variables
}
