
package capa_presentacion.mantenimiento;

import capa_datos.clsProductoDAO;
import capa_logica.clsProducto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernandez Reyes
 */
public class jdAgregarProducto extends javax.swing.JDialog {

    private int prod = 0;
    private int cant = 0;
    private int desc = 0;
    
    /**
     * Creates new form jdAgregarProducto
     */
    public jdAgregarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProductoKeyReleased(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNombreProducto)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasarDatos(int cod, int ctd) {
        try {
            clsProducto objPro = clsProductoDAO.getElemento(cod);
            int stock = objPro.getStock();
            if (ctd <= stock) {
                prod = cod;
                cant = ctd;
                String descuento = String.valueOf(JOptionPane.showInputDialog(rootPane,
                        "Ingrese el porcentaje de descuento: ", "0"));
                
                try {
                    desc = Integer.parseInt(descuento);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Stock insuficiente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    public int getProd() {
        return prod;
    }

    public void setProd(int prod) {
        this.prod = prod;
    }

    public int getCant() {
        return cant;
    }

    public void setCant(int cant) {
        this.cant = cant;
    }

    public int getDesc() {
        return desc;
    }

    public void setDesc(int desc) {
        this.desc = desc;
    }
    
    
    private void txtNombreProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProductoKeyReleased
        listarProductos();
    }//GEN-LAST:event_txtNombreProductoKeyReleased

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int cod = Integer.parseInt(String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 0)));
        
        String ctd = String.valueOf(JOptionPane.showInputDialog(rootPane, "Ingrese la cantidad: "));
        
        if (ctd != "null") {
            try {
                pasarDatos(cod, Integer.parseInt(ctd));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Cantidad no valida");
            }
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void listarProductos() {
        String estado;
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        modelo.addColumn("Estado");
        modelo.addColumn("Marca");
        modelo.addColumn("Categoria");
        
        int cantidad;
        clsProducto[] datos  = clsProductoDAO.productosxIniciales(txtNombreProducto.getText());
        if (datos == null) {
            cantidad = 0;
        } else {
            cantidad = datos.length;
        }
        
        for (int i = 0; i < cantidad; i++) {
            clsProducto objPro = datos[i];
            estado = objPro.isEstado() ? "Activo" : "Inactivo";
            
            modelo.addRow(new Object[] {
                objPro.getCodigo(),
                objPro.getNombre(),
                objPro.getPrecio(),
                objPro.getStock(),
                estado,
                objPro.getNomMarca(),
                objPro.getNomCategoria()
            });
        }
        tblProductos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
