
package capa_presentacion;

import capa_logica.clsUsuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jackh
 */
public class jdInicioSesion extends javax.swing.JDialog {

    private int captchaActual;

    /**
     * Creates new form jdInicioSesion
     * @param parent
     * @param modal
     */
    public jdInicioSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        generarNuevoCaptcha();
        cargarLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCaptcha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        txtVerificar = new javax.swing.JTextField();
        btnCambiar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Login by Fernandez :.");

        jLabel1.setText("USUARIO");

        jLabel2.setText("CLAVE");

        jLabel3.setText("CAPTCHA");

        lblCaptcha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtUsuario.setText("admin");

        txtClave.setText("1234");

        btnCambiar.setText("CAMBIAR");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnIniciarSesion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(btnCambiar))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarSesion)
                    .addComponent(btnSalir))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        
        clsUsuario objUsuario = new clsUsuario();
        
        objUsuario.setUsuario(txtUsuario.getText());
        objUsuario.setClave(txtClave.getText());
        
        // Verificar captcha
        if (!verificarCaptcha()) {
            JOptionPane.showMessageDialog(this, "El captcha ingresado es incorrecto",
                "Error de captcha", JOptionPane.ERROR_MESSAGE);
            generarNuevoCaptcha();
            txtVerificar.setText(""); // Limpiar el campo
            return;
        }
        
        if (objUsuario.iniciarSesion()) {
            JOptionPane.showMessageDialog(this, "Iniciando sesion...", "Mensaje",
                JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Cerrar la ventana de login
        } else {
            JOptionPane.showMessageDialog(this, "No tiene acceso al sistema", "Mensaje",
                JOptionPane.ERROR_MESSAGE);
            generarNuevoCaptcha();
            txtVerificar.setText("");
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        
        generarNuevoCaptcha();
        txtVerificar.setText(""); // Limpia el campo
    }//GEN-LAST:event_btnCambiarActionPerformed

    public boolean verificarCaptcha(){
        
        try {
            String captchaIngresado = txtVerificar.getText().trim();
            int captchaIngresadoInt = Integer.parseInt(captchaIngresado);
            return captchaIngresadoInt == captchaActual;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private void cargarLogo() {
        
        try {
            // En caso la imagen cargue  correctamente
            ImageIcon logo = new ImageIcon(getClass().getResource(("/img/isotipo_unprg.png")));
        
            // Redimensionar
            java.awt.Image img = logo.getImage();
            java.awt.Image imgEscalada = img.getScaledInstance(300, 91, java.awt.Image.SCALE_SMOOTH);
            ImageIcon logoEscalado = new ImageIcon(imgEscalada);
            txtLogo.setIcon(logoEscalado);
            
            // Centrar el logo
            txtLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        } catch (Exception e) {
            // En caso no encuentra el logo
            txtLogo.setText("UNPRG");
            txtLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }
    
    private void generarNuevoCaptcha(){
        
        clsUsuario objUsu = new clsUsuario();
        captchaActual = objUsu.generarAleatorio();
        lblCaptcha.setText(Integer.toString(captchaActual));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCaptcha;
    private javax.swing.JTextField txtClave;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtVerificar;
    // End of variables declaration//GEN-END:variables
}
